from pathlib import Path
import json,re
TS='2026-08-05T00:05:00+10:00'; R='06 Reviews/2026/08/2026-08-05/0005-AEST-review'; C='07 Changes/2026/08/2026-08-05/0005-AEST-changes'
order=['Ndoye','Lewis-Potter','Gusto',"O'Reilly",'Rúben','Romero','Aaronson','Scott','Mukiele','Adingra','Brooks','Schär','Maguire','Sessegnon','Barry','Garner','Zubimendi','Bogle','Hincapie','De Cuyper','F.Kadıoğlu','Cash','Shaw','Bobb','Dalot','N.Williams','Senesi','Van Hecke','Lacroix','King','Hutchinson','Vicario','A.Becker','Sánchez','Petrović','Kelleher','Verbruggen','Leno','Sels','Ekitiké']
board=Path('vault/01 Current/Current Draft Board.md'); txt=board.read_text(); rows=[[x.strip() for x in l.strip().strip('|').split('|')] for l in txt.splitlines() if re.match(r'^\| \d+ \|',l)]
sel=[r for r in rows if 116<=int(r[0])<=155]; assert len(sel)==40 and set(r[1] for r in sel)==set(order)
api={int(p['id']) for p in json.loads(Path('/tmp/bootstrap.json').read_text())['elements']}; assert all(int(r[6]) in api for r in sel); assert isinstance(json.loads(Path('/tmp/fixtures.json').read_text()),list)
old={r[1]:int(r[0]) for r in sel}; by={r[1]:r[:] for r in sel}; repl={}
for rank,n in enumerate(order,116):
 r=by[n][:]; r[0]=str(rank); r[4]='Depth' if rank<=128 else 'Endgame'; r[5]='C' if rank<=128 else 'D+'; r[8]=TS; r[9]=f'[[{R}]]'; repl[rank]=r
out=[]
for l in txt.splitlines():
 m=re.match(r'^\| (\d+) \|',l)
 if m and int(m.group(1)) in repl: l='| '+' | '.join(repl[int(m.group(1))])+' |'
 out.append(l)
board.write_text(re.sub(r'status: .*','status: cross_position_block_5_reviewed',re.sub(r'last_updated: .*',f'last_updated: {TS}','\n'.join(out)+'\n',1),1))
changed=[]
for rank,n in enumerate(order,116):
 p=Path(f"vault/02 Players/{n} - {by[n][6]}.md"); s=p.read_text(); s=re.sub(r'(?m)^(current_rank: )\d+',rf'\g<1>{rank}',s,1); s=re.sub(r'(?m)^(last_reviewed: ).*',rf'\g<1>{TS}',s,1); s+=f'\n\n## 0005-AEST cross-position comparison\n\n- Reviewed with overall ranks 121–150 and challengers 116–120 and 151–155.\n- Overall rank: **{old[n]} → {rank}**.\n- Raw expected season points came first, then minutes, role, set pieces, floor/ceiling and positional replacement value.\n- Draft-horizon injury weighting applied; short absences were minor, unknown or multi-month cases material.\n- Evidence and reversal triggers: [[{R}]].\n'; p.write_text(s); changed.append(str(p))
current=[[x.strip() for x in l.strip().strip('|').split('|')] for l in board.read_text().splitlines() if re.match(r'^\| \d+ \|',l)]
for code,pathstr in {'FWD':'vault/04 Positions/Forward.md','MID':'vault/04 Positions/Midfielder.md','DEF':'vault/04 Positions/Defender.md','GKP':'vault/04 Positions/Goalkeeper.md'}.items():
 p=Path(pathstr); s=p.read_text(); lines=[f"{x[0]}. [[02 Players/{x[1]} - {x[6]}|{x[1]}]] — {code}, {x[3]}; {x[4]} / {x[5]}; {x[7]}" for x in current if x[2]==code]; block='<!-- ranked-players:start -->\n## Players by overall rank\n\nPlayers are listed in canonical overall draft rank order.\n\n'+'\n'.join(lines)+f'\n\nSource: [[01 Current/Current Draft Board]] · generated {TS}\n<!-- ranked-players:end -->'; p.write_text(re.sub(r'last_reviewed: .*',f'last_reviewed: {TS}',re.sub(r'<!-- ranked-players:start -->.*?<!-- ranked-players:end -->',block,s,flags=re.S),1)); changed.append(pathstr)
pi=Path('/tmp/pi-status').read_text().strip(); reasons={('Lewis-Potter','Gusto'):'Lewis-Potter has the stronger raw attacking points route; Gusto receives a scarcity boost but still trails.',('Gusto',"O'Reilly"):'Gusto has the clearer attacking full-back ceiling and more established senior role.',('Barry','Garner'):'Barry has the higher direct scoring ceiling; Garner’s short dated groin absence is only a small penalty.',('Lacroix','King'):'Lacroix has the safer established minutes and defensive floor; King has the greater breakout volatility.',('Hutchinson','Vicario'):'Hutchinson’s attacking upside and outfield replacement value beat a deeper goalkeeper profile.',('Sels','Ekitiké'):'Sels offers usable season-long starts; Ekitiké remains heavily discounted by an Achilles injury with unknown return date.'}
comps=[f"- **{a} vs {b}: {a} first.** {reasons.get((a,b),'Better season-long combination of expected points, minutes, role, floor and Draft replacement value.')} Confidence: medium; reverse for material role, minutes, set-piece or long-term availability change." for a,b in zip(order,order[1:])]
rp=Path('vault')/f'{R}.md'; rp.parent.mkdir(parents=True,exist_ok=True); rp.write_text(f'''---\ntype: review\nreviewed_at: {TS}\nscope: cross-position ranks 121-150\nchallengers: 116-120 and 151-155\n---\n\n# Cross-position review — overall ranks 121–150\n\n## Changes since prior iteration\nInsertion-sorted ranks 121–150 against five players on each boundary using the canonical season-long Draft injury policy.\n\n## API reconciliation\nOfficial FPL bootstrap and fixtures fetched successfully; all 40 stable FPL IDs remained present. Premier Injuries returned HTTP **{pi}**; no unsupported return date was adopted.\n\n## Injury decisions\nGarner’s dated short groin absence received only a small penalty. Ekitiké remained heavily discounted because an Achilles injury with unknown return date is materially different from a verified short absence.\n\n## Decisive comparisons\n{chr(10).join(comps)}\n\n## Final reviewed order\n'''+ '\n'.join(f'{i}. {n}' for i,n in enumerate(order,116)) + '''\n\n## Key trade-offs\n- Ndoye and Lewis-Potter stayed ahead of the defender and goalkeeper cluster on raw attacking output.\n- Gusto rose on attacking-defender scarcity and established senior upside.\n- Barry remained above low-ceiling midfielders because forward replacement value is thinner.\n- King and Hutchinson entered the top 150 on breakout upside.\n- Goalkeepers fell behind similarly projected outfield players because the eight-manager replacement pool remains deep.\n- Ekitiké remained outside the top 150 because the Achilles injury has no reliable return date.\n\n## Next block\nOverall ranks 151–180 with challengers 146–150 and 181–185.\n\n## Validation\nRanks 1–350 remain complete and unique; ranks outside 116–155 retained their occupants.\n''')
cp=Path('vault')/f'{C}.md'; cp.parent.mkdir(parents=True,exist_ok=True); moves=[f'- {n}: **{old[n]} → {i}**' for i,n in enumerate(order,116) if old[n]!=i]; unchanged=[n for i,n in enumerate(order,116) if old[n]==i]; cp.write_text(f'''---\ntype: changes\nchanged_at: {TS}\nscope: cross-position ranks 121-150\n---\n\n# Cross-position block 5 changes\n\n## Rank changes\n{chr(10).join(moves) if moves else '- No material rank changes.'}\n\n## Important no-change decisions\n- Unchanged: {', '.join(unchanged) if unchanged else 'None'}.\n- No player outside ranks 116–155 changed global rank.\n- Garner did not receive a large short-term injury downgrade.\n- Ekitiké remained heavily discounted because the Achilles return date is unknown.\n\n## Next block\nOverall ranks 151–180 with challengers 146–150 and 181–185.\n''')
for f in ['vault/01 Current/Current Watchlist.md','vault/Home.md','vault/Wiki.md']:
 p=Path(f); p.write_text(p.read_text()+f'\n\n<!-- 0005-aest-cross-position-121-150 -->\n- Cross-position ranks 121–150 reviewed with challengers 116–120 and 151–155: [[{R}]] · [[{C}]].\n')
changed += ['vault/01 Current/Current Draft Board.md',str(rp),str(cp),'vault/01 Current/Current Watchlist.md','vault/Home.md','vault/Wiki.md']
log=Path('vault/00 Meta/Document Changelog.md'); s=log.read_text(); ev=f'https://fantasy.premierleague.com/api/bootstrap-static/; https://fantasy.premierleague.com/api/fixtures/; https://www.premierinjuries.com/injury-table.php (HTTP {pi}; no unsupported dates adopted); [[{R}]]; [[{C}]]'
for f in changed+['vault/00 Meta/Document Changelog.md']: s+=f'\n| {TS} | `{f}` | {"created" if f in [str(rp),str(cp)] else "updated"} | Cross-position ranks 121–150 with five-player boundary challengers | [[{R}]] | {ev} |'
log.write_text(s+'\n')